import 'package:flutter/material.dart';
import '../models/area.dart';

/// Maps a cuisine area name to its country flag emoji.
/// Falls back to a globe emoji for unknown areas.
String _flagForArea(String area) {
  const flags = {
    'Afghan': '🇦🇫',
    'Albanian': '🇦🇱',
    'Algerian': '🇩🇿',
    'American': '🇺🇸',
    'Andorran': '🇦🇩',
    'Angolan': '🇦🇴',
    'Antiguan, Barbudan': '🇦🇬',
    'Argentine': '🇦🇷',
    'Armenian': '🇦🇲',
    'Aruban': '🇦🇼',
    'Australian': '🇦🇺',
    'Austrian': '🇦🇹',
    'Azerbaijani': '🇦🇿',
    'Bahamian': '🇧🇸',
    'Bahraini': '🇧🇭',
    'Bangladeshi': '🇧🇩',
    'Barbadian': '🇧🇧',
    'Belarusian': '🇧🇾',
    'Belgian': '🇧🇪',
    'Belizean': '🇧🇿',
    'Beninese': '🇧🇯',
    'Bermudian': '🇧🇲',
    'Bhutanese': '🇧🇹',
    'Bolivian': '🇧🇴',
    'Bosnian, Herzegovinian': '🇧🇦',
    'Brazilian': '🇧🇷',
    'British': '🇬🇧',
    'Bruneian': '🇧🇳',
    'Bulgarian': '🇧🇬',
    'Burkinabe': '🇧🇫',
    'Burmese': '🇲🇲',
    'Burundian': '🇧🇮',
    'Cambodian': '🇰🇭',
    'Cameroonian': '🇨🇲',
    'Canadian': '🇨🇦',
    'Cape Verdian': '🇨🇻',
    'Caymanian': '🇰🇾',
    'Central African': '🇨🇫',
    'Chadian': '🇹🇩',
    'Channel Islander': '🇬🇬',
    'Chilean': '🇨🇱',
    'Chinese': '🇨🇳',
    'Colombian': '🇨🇴',
    'Congolese': '🇨🇩',
    'Costa Rican': '🇨🇷',
    'Croatian': '🇭🇷',
    'Cuban': '🇨🇺',
    'Cypriot': '🇨🇾',
    'Czech': '🇨🇿',
    'Danish': '🇩🇰',
    'Djibouti': '🇩🇯',
    'Dominican': '🇩🇴',
    'Dutch': '🇳🇱',
    'Ecuadorean': '🇪🇨',
    'Egyptian': '🇪🇬',
    'Emirati': '🇦🇪',
    'Equatorial Guinean': '🇬🇶',
    'Eritrean': '🇪🇷',
    'Estonian': '🇪🇪',
    'Ethiopian': '🇪🇹',
    'Faroese': '🇫🇴',
    'Fijian': '🇫🇯',
    'Filipino': '🇵🇭',
    'Finnish': '🇫🇮',
    'French': '🇫🇷',
    'Gabonese': '🇬🇦',
    'Gambian': '🇬🇲',
    'Georgian': '🇬🇪',
    'German': '🇩🇪',
    'Ghanaian': '🇬🇭',
    'Gibraltar': '🇬🇮',
    'Greek': '🇬🇷',
    'Greenlandic': '🇬🇱',
    'Grenadian': '🇬🇩',
    'Guadeloupian': '🇬🇵',
    'Guamanian': '🇬🇺',
    'Guatemalan': '🇬🇹',
    'Guinean': '🇬🇳',
    'Guinea-Bissauan': '🇬🇼',
    'Guyanese': '🇬🇾',
    'Haitian': '🇭🇹',
    'Honduran': '🇭🇳',
    'Hong Konger': '🇭🇰',
    'Hungarian': '🇭🇺',
    'Icelander': '🇮🇸',
    'Indian': '🇮🇳',
    'Indonesian': '🇮🇩',
    'Iranian': '🇮🇷',
    'Iraqi': '🇮🇶',
    'Irish': '🇮🇪',
    'Israeli': '🇮🇱',
    'Italian': '🇮🇹',
    'Ivorian': '🇨🇮',
    'Jamaican': '🇯🇲',
    'Japanese': '🇯🇵',
    'Jordanian': '🇯🇴',
    'Kazakhstani': '🇰🇿',
    'Kenyan': '🇰🇪',
    'Kirghiz': '🇰🇬',
    'Korean': '🇰🇷',
    'Kosovar': '🇽🇰',
    'Kuwaiti': '🇰🇼',
    'Laotian': '🇱🇦',
    'Latvian': '🇱🇻',
    'Lebanese': '🇱🇧',
    'Liberian': '🇱🇷',
    'Libyan': '🇱🇾',
    'Liechtensteiner': '🇱🇮',
    'Lithuanian': '🇱🇹',
    'Luxembourger': '🇱🇺',
    'Macedonian': '🇲🇰',
    'Malagasy': '🇲🇬',
    'Malawian': '🇲🇼',
    'Malaysian': '🇲🇾',
    'Maldivan': '🇲🇻',
    'Malian': '🇲🇱',
    'Maltese': '🇲🇹',
    'Mauritian': '🇲🇺',
    'Mexican': '🇲🇽',
    'Moldovan': '🇲🇩',
    'Mongolian': '🇲🇳',
    'Montenegrin': '🇲🇪',
    'Moroccan': '🇲🇦',
    'Mosotho': '🇱🇸',
    'Motswana': '🇧🇼',
    'Mozambican': '🇲🇿',
    'Namibian': '🇳🇦',
    'Nepalese': '🇳🇵',
    'New Zealander': '🇳🇿',
    'Nicaraguan': '🇳🇮',
    'Nigerien': '🇳🇪',
    'Nigerian': '🇳🇬',
    'North Korean': '🇰🇵',
    'Norwegian': '🇳🇴',
    'Omani': '🇴🇲',
    'Pakistani': '🇵🇰',
    'Palestinian': '🇵🇸',
    'Panamanian': '🇵🇦',
    'Papua New Guinean': '🇵🇬',
    'Paraguayan': '🇵🇾',
    'Peruvian': '🇵🇪',
    'Polish': '🇵🇱',
    'Portuguese': '🇵🇹',
    'Puerto Rican': '🇵🇷',
    'Qatari': '🇶🇦',
    'Romanian': '🇷🇴',
    'Russian': '🇷🇺',
    'Rwandan': '🇷🇼',
    'Saint Lucian': '🇱🇨',
    'Salvadoran': '🇸🇻',
    'Sammarinese': '🇸🇲',
    'Samoan': '🇼🇸',
    'Saudi Arabian': '🇸🇦',
    'Senegalese': '🇸🇳',
    'Serbian': '🇷🇸',
    'Seychellois': '🇸🇨',
    'Sierra Leonean': '🇸🇱',
    'Singaporean': '🇸🇬',
    'Slovak': '🇸🇰',
    'Slovene': '🇸🇮',
    'Solomon Islander': '🇸🇧',
    'Somali': '🇸🇴',
    'South African': '🇿🇦',
    'South Korean': '🇰🇷',
    'South Sudanese': '🇸🇸',
    'Spanish': '🇪🇸',
    'Sri Lankan': '🇱🇰',
    'Sudanese': '🇸🇩',
    'Surinamer': '🇸🇷',
    'Swedish': '🇸🇪',
    'Swiss': '🇨🇭',
    'Syrian': '🇸🇾',
    'Tadzhik': '🇹🇯',
    'Taiwanese': '🇹🇼',
    'Tanzanian': '🇹🇿',
    'Thai': '🇹🇭',
    'Togolese': '🇹🇬',
    'Tongan': '🇹🇴',
    'Trinidadian': '🇹🇹',
    'Tunisian': '🇹🇳',
    'Turkish': '🇹🇷',
    'Turkmen': '🇹🇲',
    'Tuvaluan': '🇹🇻',
    'Ugandan': '🇺🇬',
    'Ukrainian': '🇺🇦',
    'Uruguayan': '🇺🇾',
    'Uzbekistani': '🇺🇿',
    'Ni-Vanuatu': '🇻🇺',
    'Venezuelan': '🇻🇪',
    'Vietnamese': '🇻🇳',
    'Yemeni': '🇾🇪',
    'Zambian': '🇿🇲',
    'Zimbabwean': '🇿🇼',
  };
  return flags[area] ?? '🌍';
}

class AreaTile extends StatelessWidget {
  final Area area;
  final VoidCallback onTap;

  const AreaTile({
    super.key,
    required this.area,
    required this.onTap,
  });

  @override
  Widget build(BuildContext context) {
    final colorScheme = Theme.of(context).colorScheme;
    return ListTile(
      leading: Container(
        width: 48,
        height: 48,
        decoration: BoxDecoration(
          color: colorScheme.primaryContainer,
          borderRadius: BorderRadius.circular(8),
        ),
        alignment: Alignment.center,
        child: Text(
          _flagForArea(area.name),
          style: const TextStyle(fontSize: 26),
        ),
      ),
      title: Text(area.name),
      subtitle: Text(
        '${area.name} cuisine',
        style: TextStyle(color: colorScheme.onSurfaceVariant),
      ),
      trailing: const Icon(Icons.chevron_right),
      onTap: onTap,
    );
  }
}
